### ISSUE TITLE
pre-trained model weight mismatched

### ISSUE THREAD

**Issue by cook-kuk** [DeepMIALab/AI-FFPE#2]
hello

I really want to test your Algorithm. (for test only, not for training)

However, the pre-trained model does not match the defined model. (I used the CUT model for now, and I used the model in Lung/CUT from the pre-trained model you provided)

Check the test command line again.

<img width="796" alt="스크린샷 2023-01-26 오후 2 42 37" src="https://user-images.githubusercontent.com/60030735/214784740-50f9e5ee-552a-4f97-aff6-034d307b08fc.png">

**Comment by Kutsev-Ozyoruk** [comment]
Hi,
Since there is a SAB integration in our model, you should use CUT repo to test this model.
Best,

**Comment by cook-kuk** [comment]
you mean i should use original cut repo??? (https://github.com/taesungp/contrastive-unpaired-translation)

**Comment by Kutsev-Ozyoruk** [comment]
Sure, you can only test the models in Frozgan folder with our repo since
these are our method's model. Otherwise you have to use the corresponding
repo to test the model.
